/**
 * Standardized Application Error Codes
 * Used across frontend and backend for programmatic error classification and localization.
 */
export const ErrorCode = {
  // 400 Bad Request / Validation
  BAD_REQUEST: "BAD_REQUEST",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_INPUT: "INVALID_INPUT",
  INVALID_ID_FORMAT: "INVALID_ID_FORMAT",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  UNSUPPORTED_FILE_TYPE: "UNSUPPORTED_FILE_TYPE",

  // 401 Unauthorized
  UNAUTHORIZED: "UNAUTHORIZED",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",

  // 403 Forbidden
  FORBIDDEN: "FORBIDDEN",
  INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",
  ROLE_MISMATCH: "ROLE_MISMATCH",

  // 404 Not Found
  NOT_FOUND: "NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  COURSE_NOT_FOUND: "COURSE_NOT_FOUND",
  ASSIGNMENT_NOT_FOUND: "ASSIGNMENT_NOT_FOUND",
  SUBMISSION_NOT_FOUND: "SUBMISSION_NOT_FOUND",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",

  // 409 Conflict
  CONFLICT: "CONFLICT",
  DUPLICATE_KEY_ERROR: "DUPLICATE_KEY_ERROR",
  ALREADY_ENROLLED: "ALREADY_ENROLLED",
  SUBMISSION_ALREADY_EXISTS: "SUBMISSION_ALREADY_EXISTS",

  // 422 Unprocessable Entity
  UNPROCESSABLE_ENTITY: "UNPROCESSABLE_ENTITY",

  // 429 Rate Limiting
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",

  // 500 Internal Server Error
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  DATABASE_ERROR: "DATABASE_ERROR",
  STORAGE_ERROR: "STORAGE_ERROR",
  MAIL_DELIVERY_ERROR: "MAIL_DELIVERY_ERROR",
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
